MOMENTUM:
  TICK:
    threshold:
      minRelativeVolume: 0.00
      minObImbalance: 0.030
      minVolatility: 0.00
      minMACDDeviation: 0.00
      rsiOverbought: 70
      rsiOversold: 30
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config: {}
  SEC5:
    threshold:
      minRelativeVolume: 1.20
      minObImbalance: 0.10
      minVolatility: 0.035
      minMACDDeviation: 0.0010
      rsiOverbought: 70
      rsiOversold: 30
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 4.0
      bbPeriod: 20
      bbMultiplier: 2.0
      macdFast: 3
      macdSlow: 8
      macdSignal: 2
      smaPeriod: 8
      rsiPeriod: 14
  SEC10:
    threshold:
      minRelativeVolume: 1.00
      minObImbalance: 0.09
      minVolatility: 0.025
      minMACDDeviation: 0.0015
      rsiOverbought: 70
      rsiOversold: 30
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 3.5
      bbPeriod: 20
      bbMultiplier: 2.0
      macdFast: 4
      macdSlow: 8
      macdSignal: 3
      smaPeriod: 10
      rsiPeriod: 14
PULLBACK:
  TICK:
    threshold:
      minRelativeVolume: 0.00
      minObImbalance: 0.035
      minVolatility: 0.00
      minMACDDeviation: 0.00
      rsiOverbought: 70
      rsiOversold: 35
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config: {}
  SEC10:
    threshold:
      minRelativeVolume: 1.10
      minObImbalance: 0.10
      minVolatility: 0.025
      minMACDDeviation: 0.0035
      rsiOverbought: 70
      rsiOversold: 35
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 3.5
      bbPeriod: 20
      bbMultiplier: 2.0
      macdFast: 6
      macdSlow: 13
      macdSignal: 5
      smaPeriod: 12
      rsiPeriod: 16
  SEC30:
    threshold:
      minRelativeVolume: 1.00
      minObImbalance: 0.10
      minVolatility: 0.022
      minMACDDeviation: 0.005
      rsiOverbought: 70
      rsiOversold: 35
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 3.0
      bbPeriod: 20
      bbMultiplier: 2.0
      macdFast: 6
      macdSlow: 13
      macdSignal: 5
      smaPeriod: 14
      rsiPeriod: 16
  MIN1:
    threshold:
      minRelativeVolume: 0.90
      minObImbalance: 0.08
      minVolatility: 0.018
      minMACDDeviation: 0.007
      rsiOverbought: 70
      rsiOversold: 35
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 2.5
      bbPeriod: 20
      bbMultiplier: 2.0
      macdFast: 6
      macdSlow: 13
      macdSignal: 5
      smaPeriod: 16
      rsiPeriod: 16

RANGE:
  TICK:
    threshold:
      minRelativeVolume: 0.00
      minObImbalance: 0.05
      minVolatility: 0.00
      minMACDDeviation: 0.00
      rsiOverbought: 70
      rsiOversold: 30
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config: {}
  SEC5:
    threshold:
      minRelativeVolume: 1.05
      minObImbalance: 0.10
      minVolatility: 0.025
      minMACDDeviation: 0.0035
      rsiOverbought: 70
      rsiOversold: 35
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 3.5
      bbPeriod: 20
      bbMultiplier: 2.0
      macdFast: 6
      macdSlow: 13
      macdSignal: 5
      smaPeriod: 12
      rsiPeriod: 16
  SEC30:
    threshold:
      minRelativeVolume: 0.9
      minObImbalance: 0.07
      minVolatility: 0.015
      minMACDDeviation: 0.002
      rsiOverbought: 70
      rsiOversold: 30
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 2.0
      bbPeriod: 20
      bbMultiplier: 2.0
      macdFast: 7
      macdSlow: 14
      macdSignal: 5
      smaPeriod: 16
      rsiPeriod: 16
  MIN1:
    threshold:
      minRelativeVolume: 0.85
      minObImbalance: 0.06
      minVolatility: 0.012
      minMACDDeviation: 0.0015
      rsiOverbought: 70
      rsiOversold: 30
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 1.5
      bbPeriod: 20
      bbMultiplier: 2.0
      macdFast: 7
      macdSlow: 14
      macdSignal: 5
      smaPeriod: 20
      rsiPeriod: 20

NEWS:
  TICK:
    threshold:
      minRelativeVolume: 0.00
      minObImbalance: 0.025
      minVolatility: 0.00
      minMACDDeviation: 0.00
      rsiOverbought: 75
      rsiOversold: 25
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config: {}
  SEC5:
    threshold:
      minRelativeVolume: 1.5
      minObImbalance: 0.18
      minVolatility: 0.05
      minMACDDeviation: 0.0005
      rsiOverbought: 75
      rsiOversold: 25
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 6.0
      bbPeriod: 20
      bbMultiplier: 2.5
      macdFast: 5
      macdSlow: 13
      macdSignal: 3
      smaPeriod: 6
      rsiPeriod: 14
  SEC10:
    threshold:
      minRelativeVolume: 1.30
      minObImbalance: 0.16
      minVolatility: 0.04
      minMACDDeviation: 0.0008
      rsiOverbought: 75
      rsiOversold: 25
      vwapTrendOK: true
      bbTrendOK: true
      trendOK: true
      smaTrendOK: true
    config:
      pullbackPercent: 5.0
      bbPeriod: 20
      bbMultiplier: 2.5
      macdFast: 5
      macdSlow: 13
      macdSignal: 3
      smaPeriod: 8
      rsiPeriod: 14